### ISSUE TITLE
DifferentialChangesetTwoUpRenderer

### ISSUE THREAD

**Issue by aalmazzo** [ipsGre/phabricator_sonar_plugin#1]
Steps to reproduce:
1. Install latest Phabricator version:
   https://github.com/phacility/phabricator.git
2. Python version: 2.7.10
3. PHP version: 5.5.27
4. Restart apache
5. Go to your local Phabricator

> > > UNRECOVERABLE FATAL ERROR <<<

Class DifferentialChangesetTwoUpRenderer contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (DifferentialChangesetHTMLRenderer::getRendererTableClass, DifferentialChangesetHTMLRenderer::getRowScaffoldForInline, DifferentialChangesetRenderer::getRendererKey)

~/phabricatorServer/tools/phabricator/src/extensions/phabricator_sonar_plugin/src/DifferentialChangesetTwoUpRenderer.php:4

┻━┻ ︵ ¯_(ツ)_/¯ ︵ ┻━┻

**Comment by aalmazzo** [comment]
Fixed with:

protected function getRendererTableClass() {
    return 'diff-2up';
  }

  public function getRowScaffoldForInline(PHUIDiffInlineCommentView $view) {
    return id(new PHUIDiffTwoUpInlineCommentRowScaffold())
        ->addInlineView($view);
  }

  public function getRendererKey() {
    return '2up';
  }

**Comment by octera** [comment]
Please make a PR I will integrate asap

**Comment by aalmazzo** [comment]
That uncovered a second issue:

[Wed Oct 28 12:00:20.398811 2015] [:error] [pid 81395] [client 127.0.0.1:56361] [2015-10-28 12:00:20] ERROR 8: Undefined offset: 5 at [/Users/antonio.almazzo/workspace/phabricator_sonar_plugin/src/DifferentialLineNumberRendered.php:137]
[Wed Oct 28 12:00:20.399219 2015] [:error] [pid 81395] [client 127.0.0.1:56361] arcanist(head=master, ref.master=3308da5f8fbe), phabricator(head=master, ref.master=43569d4e278c), phutil(head=master, ref.master=fe7d8c21a808)
[Wed Oct 28 12:00:20.399229 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #0 DifferentialLineNumberRendered::getLineTag(integer) called at [/Users/antonio.almazzo/workspace/phabricator_sonar_plugin/src/DifferentialChangesetTwoUpRenderer.php:328]
[Wed Oct 28 12:00:20.399233 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #1 DifferentialChangesetTwoUpRenderer::renderTextChange(integer, integer, integer) called at [<phabricator>/src/applications/differential/parser/DifferentialChangesetParser.php:1130]
[Wed Oct 28 12:00:20.399247 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #2 DifferentialChangesetParser::render(NULL, NULL, array) called at [<phabricator>/src/applications/differential/parser/DifferentialChangesetParser.php:72]
[Wed Oct 28 12:00:20.399250 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #3 DifferentialChangesetParser::renderChangeset() called at [<phabricator>/src/applications/differential/controller/DifferentialChangesetViewController.php:256]
[Wed Oct 28 12:00:20.399253 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #4 DifferentialChangesetViewController::handleRequest(AphrontRequest) called at [<phabricator>/src/aphront/configuration/AphrontApplicationConfiguration.php:237]
[Wed Oct 28 12:00:20.399256 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #5 AphrontApplicationConfiguration::processRequest(AphrontRequest, PhutilDeferredLog, AphrontPHPHTTPSink, MultimeterControl) called at [<phabricator>/src/aphront/configuration/AphrontApplicationConfiguration.php:149]
[Wed Oct 28 12:00:20.399259 2015] [:error] [pid 81395] [client 127.0.0.1:56361]   #6 AphrontApplicationConfiguration::runHTTPRequest(AphrontPHPHTTPSink) called at [<phabricator>/webroot/index.php:17]
